framework:
    notifier:
        chatter_transports:
        #    slack: '%env(SLACK_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
            google_chat: '%env(GOOGLE_CHAT_DSN)%'
        #texter_transports:
        #    twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['chat']
            high: ['chat']
            medium: ['chat']
            low: ['chat']
        admin_recipients:
            - { email: admin@example.com }