twig:
    default_path: '%kernel.project_dir%/templates/'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    paths:
#        'templates/_themes/default': ~
        'templates/_themes/%env(APP_THEME)%': ~
        #'templates/_themes/tabler': ~